# Generated by Django 3.0.8 on 2020-09-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20200903_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
